---
title: " 用R进行数据分析和数据可视化"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```




## 项目描述:

为了方便大家更高效地用R完成数据分析和数据可视化的工作，我们开发了R包“dppbar”，它基本上包含了目前使用过的所有画图工具及一些数据处理方法。基于我们之前的工作经历，有时候想用R来画出符合预期的图或者按需要处理数据并不容易，网上虽然充斥着大量的学习资源，但是往往很难准确的找到我们面临的问题的解决方案；另一方面，如果不对面对的问题加以妥善总结和记录，未来编程时还可能碰上同样的问题，经受同样的折磨；这种工作方式显然是非常低效的。为了在一定程度上帮大家避免这一问题，从而能把经历更多的投入到洞见的思考和模型的构建上，我们也一并设立了本网站以方便大家查找关于工具包“dppbar”的使用方法和帮助。同时我们也加入了博客标签页，欢迎大家记录工作中面临的技术问题和解决方案。最后要说的是，由于我们的工作一定程度上属于创造性的工作，因此模范化的工具包虽然能提高生产的效率，但也有可能阻碍开拓性思维的发展。因此，我们希望大家不要局限于这个工具包的函数，而是以此为基础，丰富它的内容。大家如有其它更好的关于用R进行数据分析和可视化的创意，也十分欢迎与我联系，我们可以不断更新这个工具包，使它在将来能具备更广的应用场景。

## 函数分类:

工具包中包含的函数主要可分为以下几个大类:

1. **数据预处理函数:** 在数值型变量与字符型变量间转换、填补数据集中的空缺值、获得数据集的一些统计特征

2. **数据可视化函数:** 常用的画图函数，可以用来发现数据的分布规律

3. **数据基本分析函数:** 用来对数据进行基本的回归或者插值的函数

## List of functions and their features:

下面的表格汇总了工具包中主要的函数及其用途。这个表格将随工具包一起更新

R中的函数名                    | 函数的用途
-------------------------------|--------------------------------------
**数据预处理函数**             |
column_class()                 | 将数据集中的变量按数值型和字符型分类
num2ctg()                      | 将数值型变量转为字符型变量
ord_ctg2num()                  | 有序字符型变量转为数值型变量
nom_ctg2num()                  | 无序字符型变量转为数值型变量
impute_missing()               | 通过MICE方法来填补空缺值
**数据可视化函数**             | 
bar_plot()                     | 堆叠的柱状图展示多个类别变量的分布信息
bubble_plot()                  | 通过颜色和大小展示更多信息的气泡图
corr_check()                   | 变量间相关关系检验图
distribution_plot()            | 包含三种输出形式的数值型变量分布图
donut_plot()                   | 甜甜圈图展示类别变量的百分比
double_axis()                  | 在一张图中通过两个y轴叠加折线图和柱状图
facet_bar()                    | 通过子窗口将大柱状图细分
horizontal_bar()               | 横向柱状图同时展示多个类别的百分比
label_bar_plot()               | 带小标签的柱状图
lines_plot()                   | 基本折线图
lines_split_plot()             | 通过子图绘制范围差别较大的折线图
line_ann_plot()                | 通过标点和附注丰富折线图信息
polar_cahrts()                 | 雷达图
rank_plot()                    | 用折线图展示样本的排名变化
**数据基本分析函数**           | 
cal_pct()                      | 计算各个类别的占比
get_rank()                     | 计算各个类别的排序
lin_predict()                  | 通过动态线性模型实现外插值（预测）
plm_basic()                    | 通过逐步筛选变量的方式获得基本的面板回归模型


